"""empty message

Revision ID: b989086429b9
Revises: a31a4508f5ee
Create Date: 2017-11-16 15:48:06.508821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b989086429b9'
down_revision = 'a31a4508f5ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_student', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_student', type_='unique')
    # ### end Alembic commands ###
