"""empty message

Revision ID: ed778eb68c3a
Revises: 303f14d5aa6b
Create Date: 2017-11-16 23:28:16.270540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed778eb68c3a'
down_revision = '303f14d5aa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tbl_student_pin_key', 'tbl_student', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'tbl_student_pin_key', 'tbl_student', ['pin'])
    # ### end Alembic commands ###
